import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthContextProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col bg-[url('/light.png')] dark:bg-[url('/dark.png')] bg-cover bg-no-repeat text-black dark:text-white`}
      >
        <AuthContextProvider>
          <ThemeProvider>
            <Navbar />
            <main className="flex-grow h-full flex">
              {children}
            </main>
            <ToastContainer />
          </ThemeProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
